version: '2.4'
services: 
  examples2:
    image: 511023/myasr:v1.2_dist
    # Use a volume mount to point to your own scripts without rebuilding the image
    volumes:
      - /mnt/volume/workspace/myasr:/mnt/volume/workspace/myasr
      - /mnt/volume/workspace/datasets:/mnt/volume/workspace/datasets
      - /mnt/volume/workspace/datasets/librispeech/apc/extra:/mnt/volume/workspace/datasets/librispeech/apc/extra
    #   - /mnt/volume/workspace/datasets:/mnt/volume/workspace/datasets
    working_dir: /mnt/volume/workspace/myasr
    command:  --nnodes=3 --nproc_per_node=1 --rdzv_id=2 --rdzv_endpoint=192.168.1.108 train.py --lr 0.3 --checkpoint_path 'checkpoint/latest.pt' #--continue_learning
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    network_mode: 'host'
